name: Build SubSonicEnum

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nvidia-cuda-toolkit gcc-12 g++-12
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_CUDA_COMPILER=/opt/cuda/bin/nvcc
        make